# Site settings
title: 老杨记事儿
tagline: 生活笔记，学习心得
email: N/A
description: > # this means to ignore newlines until "baseurl:"
  这家伙很懒，什么都没留下。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yangzhiyong.com" # the base hostname & protocol for your site
twitter_username: yangzhyo
github_username:  yangzhyo
weibo_username:   unclemao
facebook_username: johnzyoung

# Build settings
markdown: kramdown
highlighter: pygments
paginate: 3
paginate_path: "page/:num"
